CivFix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tickets.urls")),
    path("admin/", admin.site.urls),
]

tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("profile/", views.profile, name="profile"),
    # URL pattern for upvoting
    path('upvote/<int:ticket_id>/', views.upvote_ticket, name='upvote_ticket'),
]

tickets/models.py
from django.db import models
from django.contrib.auth.models import User

class Ticket(models.Model):
    CATEGORY_CHOICES = [
        ('INFRASTRUCTURE', 'Infrastructure'),
        ('SAFETY_SECURITY', 'Safety & Security'),
        ('SANITATION_HEALTH', 'Sanitation & Health'),
        ('TRAFFIC_TRANSPORTATION', 'Traffic & Transportation'),
    ]

    STATUS_CHOICES = [
        ('OPEN', 'Open'),
        ('IN_PROGRESS', 'In progress'),
        ('RESOLVED', 'Resolved'),
        ('CLOSED', 'Closed'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='INFRASTRUCTURE')
    status = models.CharField(max_length=255, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, related_name='tickets', on_delete=models.CASCADE, default='admin')

    def __str__(self):
        return self.title

    def calculate_total_upvote(self):
        pass
        # return self.upvote_set.count()

class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    ticket = models.ForeignKey(Ticket, related_name='upvotes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    vote_weight = models.IntegerField(default=1)

    class Meta:
        unique_together = [('user', 'ticket'), ('session_key', 'ticket')]
        index_together = [['user', 'ticket'], ['session_key', 'ticket']]

    def __str__(self):
        username = self.user.username if self.user else 'Anonymous'
        return f"{username} upvoted {self.ticket.title}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)

    def add_points(self, points):
        self.points += points
        self.save()

    def __str__(self):
        return self.user.username

tickets/forms.py
from django import forms


class TicketForm(forms.Form):
    CATEGORY_CHOICES = [
        ('INFRASTRUCTURE', 'Infrastructure'),
        ('SAFETY_SECURITY', 'Safety & Security'),
        ('SANITATION_HEALTH', 'Sanitation & Health'),
        ('TRAFFIC_TRANSPORTATION', 'Traffic & Transportation'),
    ]

    STATUS_CHOICES = [
        ('OPEN', 'Open'),
        ('IN_PROGRESS', 'In progress'),
        ('RESOLVED', 'Resolved'),
        ('CLOSED', 'Closed'),
    ]

    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(choices=CATEGORY_CHOICES, initial='INFRASTRUCTURE')
    # status = forms.ChoiceField(choices=STATUS_CHOICES, initial='OPEN')
    # creator = forms.CharField(initial='admin')

    # def clean_title(self):
    #     title = self.cleaned_data.get('title')
    #     if not title:
    #         raise forms.ValidationError('This field is required.')
    #     return title
    #
    # def clean_description(self):
    #     description = self.cleaned_data.get('description')
    #     if not description:
    #         raise forms.ValidationError('This field is required.')
    #     return description
    #
    # def clean_location(self):
    #     title = self.cleaned_data.get('location')
    #     if not title:
    #         raise forms.ValidationError('This field is required.')
    #     return title
    #
    # def clean_category(self):
    #     category = self.cleaned_data.get('category')
    #     if not category:
    #         raise forms.ValidationError('This field is required.')
    #     return category

tickets/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import TicketForm
from .models import Ticket, Upvote, Profile
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponseRedirect


def home(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            admin_user = User.objects.get(username='admin')
            Ticket.objects.create(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                category=form.cleaned_data['category'],
                location=form.cleaned_data['location'],
                status='OPEN',
                creator=admin_user
            )
            return redirect('tickets:home')
        else:
            print(form.errors)
            tickets = Ticket.objects.all().order_by('-created_at')
            return render(request, 'home.html', {'form': form, 'tickets': tickets})
    else:
        form = TicketForm()
        tickets = Ticket.objects.all().order_by('-created_at')
        return render(request, 'home.html', {'form': form, 'tickets': tickets})


@csrf_exempt
@require_POST
def upvote_ticket(request, ticket_id):
    # Get the ticket object or return a 404 not found response
    ticket = get_object_or_404(Ticket, id=ticket_id)
    user = request.user
    session_key = request.session.session_key or ''

    upvote, created = Upvote.objects.get_or_create(
        user=user if user.is_authenticated else None,
        session_key=session_key if not user.is_authenticated else '',
        ticket=ticket,
        defaults={'vote_weight': 1}
    )

    if not created:
        # simply ignore the second upvote
        return JsonResponse({
            'success': False,
            'message': 'You have already upvoted this ticket.',
            'upvote_count': ticket.upvotes.count()  # Sending the current upvote count back
        })

    # Get or create the user's profile
    creator_profile, profile_created = Profile.objects.get_or_create(user=ticket.creator)

    if created:
        pass

    # Use the model's method to add points
    creator_profile.add_points(2)

    # Increase the ticket upvotes and save
    upvote_count = ticket.upvotes.count()

    # return render(request, 'home.html')
    # Return a JSON response indicating success
    return JsonResponse({
        'status': 'success',
        'message': 'Thank you for upvoting!',
        'upvote_count': upvote_count
    })


def profile(request):
    query = request.GET.get('username', '') # Gets the username query from the request
    if query:
        user = User.objects.filter(username__iexact=query).first() # Find the user by username
        if user:
            profile = Profile.objects.get(user=user)
            # Your logic to gather additional data for the user profile goes here
            # ...
            context = {'profile': profile}
            return render(request, 'profile.html', context)
        else:
            # User not found, render some error or a blank profile template
            return render(request, 'profile.html', {'error': 'User not found'})
    else:
        # Default profile page when no search query is present
        # You can also handle this to show the profile of the logged-in user or some default content
        return render(request, 'profile.html')


def leaderboard(request):
    leaderboard_users = Profile.objects.order_by('-points')[:10]  # Get top 10 users
    return render(request, 'leaderboard.html', {'leaderboard_users': leaderboard_users})

tickets/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CivFix{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block extrahead %}{% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% block extrafooter %}{% endblock %}
</body>
</html>

tickets/templates/home.html
{% extends 'base.html' %}

{% block title %}Home - CivFix{% endblock %}

{% block content %}
    <div class="container">
<button type="button" class="btn btn-warning btn-lg" style="margin-top: 20px;" data-bs-toggle="modal" data-bs-target="#model">Add Ticket</button>
<div class="modal fade" id="model">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post" action="{% url 'tickets:home' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-header">
                    <button class="btn-close" data-bs-dismiss="modal" data-bs-target="#model"></button>
                </div>
                <div class="modal-body">
                    {{ form.title.label_tag }}
                    {{ form.title }}
                    {{ form.location.label_tag }}
                    {{ form.location }}
                    {{ form.description.label_tag }}
                    {{ form.description }}
                    <br>
                    {{ form.category.label_tag }}
                    {{ form.category }}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

    </div>

    <div class="container">
        <div class="row-cols-auto">
            {% for ticket in tickets %}
            <div class="col">
                <div class="box">
                    <div class="card" style="margin-top: 20px;">
                        <div class="card-body">
                            <h2 class="card-title text-primary">{{ ticket.title }}</h2>
                                <div class="card-subtitle">Created by: {{ ticket.creator }}</div>
                                <span class="cart-subtitle">Created on: {{ ticket.created_at }}</span>
                                <div class="card-text">Location: {{ ticket.location }} </div>
                                <div class="card-text">Category: {{ ticket.category }} </div>
                                <div class="card-text">Description: {{ ticket.description }}</div>
                                <div class="card-text">Status: {{ ticket.status }}</div>
                                <div class="container" style="display: flex; margin-top: 2px;">
                                    <button type="button" class="upvote-btn btn btn-success" data-ticket-id="{{ ticket.id }}" style="margin-left: -10px; margin-right: 10px;" >👍</button>
                                    <h4 id="upvote-count-{{ ticket.id }}" style="margin-top: 5px;">{{ ticket.upvotes.count }}</h4>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

   <script>
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

const csrftoken = getCookie('csrftoken');

document.addEventListener('DOMContentLoaded', function() {
    var upvoteButtons = document.querySelectorAll('.upvote-btn');

    upvoteButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            var ticketId = this.getAttribute('data-ticket-id');

            fetch('/upvote/' + ticketId + '/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },
            })
            .then(response => {
                if (!response.ok) {
                    return response.text().then(text => { throw new Error(text) });
                }
                return response.json();
            })
            .then(data => {
              if (data.success) {
                alert('Upvoted successfully!');
              } else {
                alert('Thanks for upvoting.');

              }
                const upvoteCountElement = document.getElementById(`upvote-count-${ticketId}`);

                if (upvoteCountElement) {
                  upvoteCountElement.textContent = data.upvote_count; // Updating the upvote count
                }

                }).catch(error => {
                  // Enhanced error logging
                  console.error('Error status:', error.message);
            });
        });
    });
 });
   </script>

{% endblock %}

tickets/templates/leaderboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="margin-top: 30px;">
        <h3 style="margin-bottom: 10px;">Leaderboard:</h3>
        <table class="table table-striped-columns table-bordered">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Name</th>
                    <th>Points</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                <!-- The content of the tbody would likely come from the database -->
                {% for profile in leaderboard_users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ profile.user.username }}</td>
                    <td>{{ profile.points }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">No users found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

tickets/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a href="{% url 'tickets:home' %}" class="navbar-brand"><h2>CivFix</h2></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'tickets:home' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tickets:leaderboard' %}" class="nav-link">Leaderboard</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tickets:profile' %}" class="nav-link">Profile</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

tickets/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <a href="{% url 'tickets:home' %}" class="navbar-brand"><h2>CivFix</h2></a>
            <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="nav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'tickets:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'tickets:leaderboard' %}" class="nav-link">Leaderboard</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'tickets:profile' %}" class="nav-link active">Profile</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

{% block content %}
<div class="container" style="margin-top: 20px;">
    <form method="get" action="">
        <input type="text" name="username" placeholder="Search for users..." value="{{ request.GET.username }}">
        <button type="submit">Search</button>
    </form>
    {% if profile %}
    <h1 class="text-primary">{{ profile.user }}</h1>
    <h3 class="text-success">Number of Upvotes: {{ profile.points }}</h3>
    <h3 class="text-success">Points: {{ profile.points }}</h3>
    <h3 class="text-success">Tickets generated: {{ profile.user.tickets.count }}</h3>

    <div class="container">
        <div class="row-cols-auto">
            {% for ticket in profile.user.tickets.all %}
                <div class="col">
                    <div class="box">
                        <div class="card" style="margin-top: 20px;">
                            <div class="card-body">
                                <div class="card-text">
                                    <h5>Problem: {{ ticket.description }}</h5>
                                </div>
                                <div class="card-subtitle">Date: {{ ticket.created_at|date:"Y-m-d" }}</div>
                                <div class="card-text">Category: {{ ticket.get_category_display }}</div>
                                <div class="card-text">Status: {{ ticket.status }}</div>
                                <div class="card-text">Location: {{ ticket.location }}</div>
                                <div class="card-text">Upvotes: {{ ticket.upvotes.count }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No tickets reported yet.</p>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% if not profile %}
        <h2>No user found.</h2>
    {% endif %}
</div>
{% endblock %}
</body>
</html>